language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zjy7"
  - git config user.email "zjy7@hotmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/zjy7/zjy7.github.io.git" master:master

branches:
  only:
    - master
