language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  # 添加 commit 时间戳 东8区
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  # 下面5行 防止master commit 树被清空 
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git init
  - git config user.name "zjy7"
  - git config user.email "zjy7@hotmail.com"
  - git add .
  - git commit -m "Auto Update blog content by Travis CI at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
  global:
    - GH_XXX: github.com/zjy7/zjy7.github.io.git
    # 设置GH_REF，注意更改成自己的仓库地址